apiVersion: v1
kind: ConfigMap
metadata:
  name: blablacar-config
  namespace: blablacar
data:
  POSTGRES_USER: user

  USER_DB_URL: "jdbc:postgresql://user-postgres:5432/db"

  ApiSettings__MainBaseUrl: "http://main-service:80/api"
  ApiSettings__UserBaseUrl: "http://user-service:80/api"
  ApiSettings__OrderBaseUrl: "http://order-service:80/api"
  ApiSettings__RideBaseUrl: "http://ride-service:80/api"
  ApiSettings__PaymentBaseUrl: "http://payment-service:80/api"
  ApiSettings__NotificationBaseUrl: "http://notification-service:80/api"

  RabbitMQ__HostName: rabbitmq
  RabbitMQ__Port: "5672"

---
apiVersion: v1
kind: Secret
metadata:
  name: blablacar-secret
  namespace: blablacar
type: Opaque
stringData:
  POSTGRES_PASSWORD: pass§

  RABBITMQ_USER: blabla
  RABBITMQ_PASSWORD: pass

  ConnectionStrings__Order: "Host=order-postgres;Port=5432;Database=db;Username=user;Password=pass"
  ConnectionStrings__Ride: "Host=ride-postgres;Port=5432;Database=db;Username=user;Password=pass"
  ConnectionStrings__OutboxDbContext: "Host=main-postgres;Port=5432;Database=db;Username=user;Password=pass"