apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: blablacar
spec:
  selector:
    app: main
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: blablacar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: dmytrolazarenko/main-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: blablacar-secret
                  key: RABBITMQ_USER
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: blablacar-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: blablacar-config
            - secretRef:
                name: blablacar-secret