apiVersion: v1
kind: Service
metadata:
  name: ride-service
  namespace: blablacar
spec:
  selector:
    app: ride
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride
  namespace: blablacar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride
  template:
    metadata:
      labels:
        app: ride
    spec:
      initContainers:
        - name: wait-db
          image: busybox
          command: ["sh","-c","until nc -z ride-postgres 5432; do sleep 2; done"]
      containers:
        - name: ride
          image: dmytrolazarenko/ride-service:65a426fb94c3f236fabb60b0aa71d6fda3e30623
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: blablacar-config
            - secretRef:
                name: blablacar-secret