apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-topology-init
  namespace: blablacar
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: topology-init
          image: kzholtikova/blablabla-topology:1.2
          env:
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: blablacar-secret
                  key: RABBITMQ_USER
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: blablacar-secret
                  key: RABBITMQ_PASSWORD
          envFrom:
            - configMapRef:
                name: blablacar-config
            - secretRef:
                name: blablacar-secret
      initContainers:
        - name: wait-rabbit
          image: busybox
          command: [ "sh","-c","until nc -z rabbitmq 5672; do sleep 2; done" ]